import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import { hasRole } from '@/lib/auth-utils'
import { generateMonthlyInvoices, reconcileInvoiceStatuses } from '@/lib/fee-invoices'
import type { UserRole } from '@prisma/client'

// GET /api/fees/invoices?schoolId=&year=&month=&studentId=&status=
export async function GET(request: NextRequest) {
  const session = await auth()
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { searchParams } = request.nextUrl
  const schoolId = searchParams.get('schoolId')
  const year = searchParams.get('year')
  const month = searchParams.get('month')
  const studentId = searchParams.get('studentId')
  const status = searchParams.get('status')

  if (!schoolId) return NextResponse.json({ error: 'schoolId is required' }, { status: 400 })

  const user = session.user as { id: string; role: string; schoolId?: string }

  // Students can only view their own invoices; admins can view all
  const isAdmin = hasRole(user.role as UserRole, ['SCHOOL_ADMIN', 'DEPUTY_ADMIN', 'FINANCE', 'FINANCE_MANAGER'])
  const isStudent = user.role === 'STUDENT'

  if (!isAdmin && !isStudent) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  // Recompute statuses before returning (mark overdue, etc.)
  await reconcileInvoiceStatuses(schoolId)

  const invoices = await prisma.feeInvoice.findMany({
    where: {
      schoolId,
      ...(year ? { year: parseInt(year) } : {}),
      ...(month ? { month: parseInt(month) } : {}),
      ...(studentId ? { studentId } : {}),
      ...(isStudent ? { studentId: user.id } : {}),
      ...(status ? { status: status as 'PENDING' | 'OVERDUE' | 'PAID' | 'PARTIAL' } : {}),
    },
    include: {
      student: {
        select: {
          id: true,
          firstName: true,
          lastName: true,
          admissionNumber: true,
          classId: true,
        },
      },
      schedule: {
        select: {
          id: true,
          periodType: true,
          amountDue: true,
          classId: true,
        },
      },
      payments: {
        select: { id: true, amountPaid: true, paymentDate: true, paymentMethod: true },
      },
    },
    orderBy: [{ year: 'desc' }, { month: 'desc' }, { student: { firstName: 'asc' } }],
  })

  const enriched = invoices.map((inv) => {
    const totalPaid = inv.payments.reduce((sum, p) => sum + p.amountPaid, 0)
    return {
      ...inv,
      totalPaid,
      balance: Math.max(0, inv.amountDue - totalPaid),
    }
  })

  return NextResponse.json(enriched)
}

// POST /api/fees/invoices  body: { action: 'generate', schoolId, year, month }
export async function POST(request: NextRequest) {
  const session = await auth()
  if (!session?.user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const user = session.user as { id: string; role: string }
  if (!hasRole(user.role as UserRole, ['SCHOOL_ADMIN', 'DEPUTY_ADMIN', 'FINANCE', 'FINANCE_MANAGER'])) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }

  const body = await request.json()
  const { action, schoolId, year, month, overwrite } = body

  if (action !== 'generate') {
    return NextResponse.json({ error: 'Unknown action' }, { status: 400 })
  }

  if (!schoolId || !year || !month) {
    return NextResponse.json({ error: 'schoolId, year, and month are required' }, { status: 400 })
  }

  const result = await generateMonthlyInvoices({
    schoolId,
    year: parseInt(year),
    month: parseInt(month),
    isAutoGenerated: false,
    overwrite: overwrite === true,
  })

  return NextResponse.json(result)
}
