import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { generateMonthlyInvoices } from '@/lib/fee-invoices'

/**
 * GET /api/internal/generate-invoices
 *
 * Called daily by Vercel Cron (1:00 UTC).
 * Finds all schools with auto-invoice enabled where today == invoiceDayOfMonth,
 * and generates monthly invoices for the current month.
 */
export async function GET(request: NextRequest) {
  const authHeader = request.headers.get('authorization')
  const acceptedTokens = [process.env.INTERNAL_API_TOKEN, process.env.CRON_SECRET].filter(
    (value): value is string => typeof value === 'string' && value.length > 0
  )

  if (
    acceptedTokens.length > 0 &&
    !acceptedTokens.some((token) => authHeader === `Bearer ${token}`)
  ) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const now = new Date()
  const today = now.getUTCDate()
  const currentMonth = now.getUTCMonth() + 1 // 1-12
  const currentYear = now.getUTCFullYear()

  try {
    // Get all schools where autoInvoiceEnabled=true, invoiceDayOfMonth=today,
    // and currentMonth is in invoiceActiveMonths.
    const settings = await prisma.schoolSettings.findMany({
      where: {
        autoInvoiceEnabled: true,
        invoiceDayOfMonth: today,
      },
      select: {
        schoolId: true,
        invoiceActiveMonths: true,
      },
    })

    const qualifying = settings.filter(
      (s) => s.invoiceActiveMonths.length === 0 || s.invoiceActiveMonths.includes(currentMonth)
    )

    const results: { schoolId: string; created: number; skipped: number; errors: string[] }[] = []

    for (const s of qualifying) {
      const result = await generateMonthlyInvoices({
        schoolId: s.schoolId,
        year: currentYear,
        month: currentMonth,
        isAutoGenerated: true,
        overwrite: false,
      })
      results.push({ schoolId: s.schoolId, ...result })
    }

    return NextResponse.json({
      processedSchools: results.length,
      results,
      timestamp: now.toISOString(),
    })
  } catch (error) {
    console.error('Error generating invoices:', error)
    return NextResponse.json({ error: 'Failed to generate invoices' }, { status: 500 })
  }
}
