import { prisma } from '@/lib/prisma'
import { FeeInvoiceStatus, FeePeriodType } from '@prisma/client'

export interface GenerateInvoicesOptions {
  schoolId: string
  year: number
  month: number // 1–12
  isAutoGenerated?: boolean
  overwrite?: boolean // re-generate even if invoice already exists
}

export interface GenerateInvoicesResult {
  created: number
  skipped: number
  errors: string[]
}

/**
 * Generate fee invoices for every active student for a given school/year/month.
 *
 * Logic:
 * 1. Get all APPROVED MONTHLY fee schedules for the school/year/month.
 *    A schedule with classId=null is the "flat" fallback.
 * 2. Get every student currently enrolled (not LEFT) at the school.
 * 3. For each student: find their class-specific schedule first, then flat.
 * 4. Apply per-student adjustments to compute locked amountDue.
 * 5. Skip students who already have an invoice (unless overwrite=true).
 * 6. Bulk-create FeeInvoice records.
 */
export async function generateMonthlyInvoices(
  opts: GenerateInvoicesOptions
): Promise<GenerateInvoicesResult> {
  const { schoolId, year, month, isAutoGenerated = false, overwrite = false } = opts
  const result: GenerateInvoicesResult = { created: 0, skipped: 0, errors: [] }

  // Fetch settings for due date
  const settings = await prisma.schoolSettings.findUnique({
    where: { schoolId },
    select: { feesDueDayOfMonth: true },
  })
  const dueDayOfMonth = settings?.feesDueDayOfMonth ?? 15

  // Compute due date (capped so it doesn't overflow the month)
  const daysInMonth = new Date(year, month, 0).getDate()
  const dueDay = Math.min(dueDayOfMonth, daysInMonth)
  const dueDate = new Date(year, month - 1, dueDay)

  // Fetch all approved MONTHLY schedules for this period
  const schedules = await prisma.feeSchedule.findMany({
    where: {
      schoolId,
      periodType: FeePeriodType.MONTHLY,
      status: 'APPROVED',
      year,
      month,
    },
  })

  if (schedules.length === 0) return result

  // Build lookup: classId → schedule (null classId = flat/fallback)
  const classScheduleMap = new Map<string, (typeof schedules)[0]>()
  let flatSchedule: (typeof schedules)[0] | undefined

  for (const s of schedules) {
    if (s.classId) {
      classScheduleMap.set(s.classId, s)
    } else {
      flatSchedule = s
    }
  }

  // Active students with their current class
  const students = await prisma.student.findMany({
    where: {
      schoolId,
      status: 'ACTIVE',
    },
    select: {
      id: true,
      classId: true,
    },
  })

  // Fetch all adjustments for the relevant schedule IDs and students
  const scheduleIds = schedules.map((s) => s.id)
  const studentIds = students.map((s) => s.id)

  const adjustments = await prisma.feeAdjustment.findMany({
    where: {
      schoolId,
      scheduleId: { in: scheduleIds },
      studentId: { in: studentIds },
    },
  })

  // Build: studentId+scheduleId → total adjustment
  const adjMap = new Map<string, number>()
  for (const adj of adjustments) {
    const key = `${adj.studentId}:${adj.scheduleId}`
    adjMap.set(key, (adjMap.get(key) ?? 0) + adj.amount)
  }

  // Existing invoices for this period (for skip logic)
  const existingInvoices = await prisma.feeInvoice.findMany({
    where: {
      schoolId,
      periodType: FeePeriodType.MONTHLY,
      year,
      month,
    },
    select: { studentId: true, scheduleId: true },
  })

  const existingSet = new Set(existingInvoices.map((i) => `${i.studentId}:${i.scheduleId}`))

  const toCreate: {
    schoolId: string
    studentId: string
    scheduleId: string
    periodType: FeePeriodType
    year: number
    month: number
    amountDue: number
    dueDate: Date
    status: FeeInvoiceStatus
    isAutoGenerated: boolean
  }[] = []

  for (const student of students) {
    const schedule =
      (student.classId ? classScheduleMap.get(student.classId) : undefined) ?? flatSchedule

    if (!schedule) {
      // No applicable schedule for this student
      continue
    }

    const key = `${student.id}:${schedule.id}`

    if (existingSet.has(key) && !overwrite) {
      result.skipped++
      continue
    }

    const adjustment = adjMap.get(key) ?? 0
    const amountDue = Math.max(0, schedule.amountDue + adjustment)

    toCreate.push({
      schoolId,
      studentId: student.id,
      scheduleId: schedule.id,
      periodType: FeePeriodType.MONTHLY,
      year,
      month,
      amountDue,
      dueDate,
      status: FeeInvoiceStatus.PENDING,
      isAutoGenerated,
    })
  }

  if (toCreate.length > 0) {
    if (overwrite) {
      // Delete existing then recreate
      await prisma.feeInvoice.deleteMany({
        where: {
          schoolId,
          periodType: FeePeriodType.MONTHLY,
          year,
          month,
          studentId: { in: toCreate.map((r) => r.studentId) },
        },
      })
    }

    await prisma.feeInvoice.createMany({ data: toCreate })
    result.created = toCreate.length
  }

  return result
}

/**
 * Recompute and update the status of all invoices for a school based on
 * actual payments received. Call this after recording a new payment.
 *
 * Status logic:
 * - amountPaid >= amountDue → PAID
 * - 0 < amountPaid < amountDue → PARTIAL
 * - amountPaid == 0 && dueDate < now → OVERDUE
 * - amountPaid == 0 && dueDate >= now → PENDING
 */
export async function reconcileInvoiceStatuses(schoolId: string): Promise<void> {
  const now = new Date()

  const invoices = await prisma.feeInvoice.findMany({
    where: { schoolId, status: { not: 'PAID' } },
    include: { payments: { select: { amountPaid: true } } },
  })

  const updates: Promise<unknown>[] = []

  for (const inv of invoices) {
    const totalPaid = inv.payments.reduce((sum, p) => sum + p.amountPaid, 0)
    let newStatus: FeeInvoiceStatus

    if (totalPaid >= inv.amountDue) {
      newStatus = FeeInvoiceStatus.PAID
    } else if (totalPaid > 0) {
      newStatus = FeeInvoiceStatus.PARTIAL
    } else if (inv.dueDate < now) {
      newStatus = FeeInvoiceStatus.OVERDUE
    } else {
      newStatus = FeeInvoiceStatus.PENDING
    }

    if (newStatus !== inv.status) {
      updates.push(
        prisma.feeInvoice.update({ where: { id: inv.id }, data: { status: newStatus } })
      )
    }
  }

  await Promise.all(updates)
}
