import { NextResponse } from 'next/server'
import { auth } from '@/lib/auth'
import { hasRole } from '@/lib/auth-utils'
import * as XLSX from 'xlsx'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

export async function GET() {
  try {
    const session = await auth()

    if (!session?.user || !hasRole(session.user.role, ['SCHOOL_ADMIN', 'SUPER_ADMIN'])) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const sampleStudents = [
      ['Alice', 'Johnson', '2014-05-15', 'Mary Johnson'],
      ['Brian', 'Mensah', '2014-01-12', 'Kwame Mensah'],
      ['Chloe', 'Ndlovu', '2014-07-21', 'Ruth Ndlovu'],
      ['Daniel', 'Kamau', '2013-11-03', 'Grace Kamau'],
      ['Ethan', 'Okello', '2014-02-17', 'Sarah Okello'],
      ['Fatima', 'Hassan', '2013-10-28', 'Amina Hassan'],
      ['George', 'Banda', '2014-03-09', 'Martha Banda'],
      ['Hannah', 'Otieno', '2014-06-26', 'Peter Otieno'],
      ['Isaac', 'Mwangi', '2013-12-14', 'Lucy Mwangi'],
      ['Jasmine', 'Dube', '2014-04-30', 'Patrick Dube'],
      ['Kevin', 'Achieng', '2013-09-05', 'Jane Achieng'],
      ['Lina', 'Moyo', '2014-08-19', 'Tendai Moyo'],
      ['Michael', 'Phiri', '2013-10-11', 'Mercy Phiri'],
      ['Nora', 'Chirwa', '2014-01-24', 'Victor Chirwa'],
      ['Owen', 'Abdi', '2014-02-06', 'Halima Abdi'],
      ['Priya', 'Patel', '2013-11-22', 'Raj Patel'],
      ['Quinn', 'Sibanda', '2014-05-03', 'Nomsa Sibanda'],
      ['Ruth', 'Mthembu', '2014-07-08', 'Sipho Mthembu'],
      ['Samuel', 'Mutiso', '2013-12-01', 'Ann Mutiso'],
      ['Tina', 'Zulu', '2014-03-27', 'David Zulu'],
    ]

    const templateRows = sampleStudents.map(([firstName, lastName, dateOfBirth, parentName], index) => {
      const entryNumber = String(index + 1).padStart(2, '0')
      return {
        firstName,
        lastName,
        dateOfBirth,
        className: 'Unassigned',
        classId: '',
        parentName,
        parentEmail: `${firstName.toLowerCase()}.${lastName.toLowerCase()}@parent.example.com`,
        parentPhone: `+12345678${entryNumber}`,
        emergencyContactName: `${parentName} (Emergency)`,
        emergencyContactPhone: `+12345000${entryNumber}`,
      }
    })

    const workbook = XLSX.utils.book_new()
    const worksheet = XLSX.utils.json_to_sheet(templateRows)

    const instructions = [
      ['Required columns:', 'firstName, lastName, className OR classId'],
      ['Optional columns:', 'dateOfBirth, parentName, parentEmail, parentPhone, emergencyContactName, emergencyContactPhone'],
      ['Admission number:', 'Auto-generated by system as ADM-<year>-<4 digits>'],
      ['Date format:', 'YYYY-MM-DD'],
      ['Parent email/phone:', 'Optional contact details'],
      ['Emergency contact:', 'Optional name and phone number'],
    ]

    const instructionsSheet = XLSX.utils.aoa_to_sheet(instructions)

    XLSX.utils.book_append_sheet(workbook, worksheet, 'Students Template')
    XLSX.utils.book_append_sheet(workbook, instructionsSheet, 'Instructions')

    const buffer = XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' })

    return new NextResponse(buffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'Content-Disposition': 'attachment; filename="students-bulk-upload-template.xlsx"',
        'Cache-Control': 'no-store',
      },
    })
  } catch (error) {
    console.error('Error generating students template:', error)
    return NextResponse.json({ error: 'Failed to generate template' }, { status: 500 })
  }
}
