import { NextResponse } from 'next/server'
import { auth } from '@/lib/auth'
import { hasRole } from '@/lib/auth-utils'
import * as XLSX from 'xlsx'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

export async function GET() {
  try {
    const session = await auth()

    if (!session?.user || !hasRole(session.user.role, ['SCHOOL_ADMIN', 'SUPER_ADMIN'])) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const templateRows = [
      {
        firstName: 'Alice',
        lastName: 'Johnson',
        dateOfBirth: '2014-05-15',
        className: 'Grade 5A',
        classId: '',
        parentName: 'Mary Johnson',
        parentEmail: 'mary.johnson@example.com',
        parentPhone: '+1234567890',
        emergencyContactName: 'John Johnson',
        emergencyContactPhone: '+1234567000',
      },
      {
        firstName: 'Brian',
        lastName: 'Mensah',
        dateOfBirth: '2013-09-02',
        className: 'Grade 5A',
        classId: '',
        parentName: 'Kwame Mensah',
        parentEmail: '',
        parentPhone: '',
        emergencyContactName: '',
        emergencyContactPhone: '',
      },
    ]

    const workbook = XLSX.utils.book_new()
    const worksheet = XLSX.utils.json_to_sheet(templateRows)

    const instructions = [
      ['Required columns:', 'firstName, lastName, className OR classId'],
      ['Optional columns:', 'dateOfBirth, parentName, parentEmail, parentPhone, emergencyContactName, emergencyContactPhone'],
      ['Admission number:', 'Auto-generated by system as ADM-<year>-<4 digits>'],
      ['Date format:', 'YYYY-MM-DD'],
      ['Parent email/phone:', 'Optional contact details'],
      ['Emergency contact:', 'Optional name and phone number'],
    ]

    const instructionsSheet = XLSX.utils.aoa_to_sheet(instructions)

    XLSX.utils.book_append_sheet(workbook, worksheet, 'Students Template')
    XLSX.utils.book_append_sheet(workbook, instructionsSheet, 'Instructions')

    const buffer = XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' })

    return new NextResponse(buffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'Content-Disposition': 'attachment; filename="students-bulk-upload-template.xlsx"',
        'Cache-Control': 'no-store',
      },
    })
  } catch (error) {
    console.error('Error generating students template:', error)
    return NextResponse.json({ error: 'Failed to generate template' }, { status: 500 })
  }
}
